name: Sponsor Update

on:
  - push
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - name: Read sponsors.md
        id: sponsors
        uses: juliangruber/read-file-action@v1
        with:
          path: ./sponsors.md
      - uses: mingjun97/regex-property-action@v1
        with:
          regex: '(## Sponsors.)(^.*)(##)'
          replacement: '$1${{ steps.sponsors.outputs.content }}$3'
          include: 'README.md'
          flags: 'gsm'
      - uses: actions/upload-artifact@v2  # upload to artifact to see the changes
        with:
          name: test
          path: |
            README.md