name: Sponsor Update

on:
  push:
    branches:
      - master
    paths:
      - sponsors.md
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - name: Read sponsors.md
        id: sponsors
        uses: juliangruber/read-file-action@v1
        with:
          path: ./sponsors.md
      - uses: mingjun97/regex-property-action@v1
        with:
          regex: '(## Sponsors.)(^.*)(##)'
          replacement: '$1${{ steps.sponsors.outputs.content }}$3'
          include: 'README.md'
          flags: 'gsm'
      - name: push
        uses: actions-x/commit@v2
        with:
          email: jneilliii+github@gmail.com
          name: jneilliii
          message: Update Sponsors
          files: README.md
          token: ${{ secrets.PERSONAL_TOKEN }}